# Generated by Django 5.2.7 on 2025-10-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='rooster/')),
            ],
            options={
                'permissions': [('can_access_admin', 'Mag beheer openen'), ('can_manage_users', 'Mag gebruikers beheren'), ('can_view_roster', 'Mag rooster bekijken'), ('can_upload_roster', 'Mag roosters uploaden'), ('can_access_availability', 'Mag Beschikbaarheid openen'), ('can_view_av_medications', 'Mag subtab Geneesmiddelen zien'), ('can_view_av_nazendingen', 'Mag subtab Nazendingen zien'), ('can_view_news', 'Mag Nieuws bekijken'), ('can_view_policies', 'Mag Werkafspraken bekijken')],
            },
        ),
    ]
