# Generated by Django 5.2.7 on 2025-10-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Rooster', max_length=200)),
                ('pdf', models.FileField(upload_to='rosters/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hash16', models.CharField(blank=True, max_length=16)),
                ('page_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
