# Generated by Django 5.2.7 on 2025-10-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roster',
            options={'permissions': [('can_access_admin', 'Mag beheer openen'), ('can_manage_users', 'Mag gebruikers beheren'), ('can_view_roster', 'Mag rooster bekijken'), ('can_upload_roster', 'Mag roosters uploaden'), ('can_access_availability', 'Mag Beschikbaarheid openen'), ('can_view_av_medications', 'Mag subtab Geneesmiddelen zien'), ('can_upload_voorraad', 'Mag Voorraad uploaden'), ('can_view_av_nazendingen', 'Mag subtab Nazendingen zien'), ('can_upload_nazendingen', 'Mag Nazendingen uploaden'), ('can_view_news', 'Mag Nieuws bekijken'), ('can_view_policies', 'Mag Werkafspraken bekijken')]},
        ),
        migrations.AddField(
            model_name='roster',
            name='pages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='roster',
            name='file',
            field=models.FileField(null=True, upload_to='rooster/current.pdf'),
        ),
    ]
