# Generated by Django 5.2.7 on 2025-10-03 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roster',
            options={'permissions': [('can_view_upload_tab', 'Mag upload-tab zien'), ('can_view_users_tab', 'Mag users-tab zien'), ('can_upload_roster', 'Mag roosters uploaden'), ('can_manage_users', 'Mag gebruikers beheren')]},
        ),
    ]
