# Generated by Django 5.2.7 on 2025-10-03 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_roster_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roster',
            options={'permissions': [('can_access_admin', 'Mag beheer openen'), ('can_upload_roster', 'Mag roosters uploaden'), ('can_manage_users', 'Mag gebruikers beheren'), ('can_view_roster', 'Mag rooster bekijken'), ('can_access_availability', 'Mag Beschikbaarheid openen'), ('can_view_av_medications', 'Mag subtab Geneesmiddelen zien'), ('can_view_av_nazendingen', 'Mag subtab Nazendingen zien')]},
        ),
    ]
