# Generated by Django 5.2.7 on 2025-10-05 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_roster_options_roster_pages_alter_roster_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roster',
            options={'permissions': [('can_access_admin', 'Mag beheer openen'), ('can_manage_users', 'Mag gebruikers beheren'), ('can_view_roster', 'Mag rooster bekijken'), ('can_upload_roster', 'Mag roosters uploaden'), ('can_access_availability', 'Mag Beschikbaarheid openen'), ('can_view_av_medications', 'Mag subtab Geneesmiddelen zien'), ('can_upload_voorraad', 'Mag Voorraad uploaden'), ('can_view_av_nazendingen', 'Mag subtab Nazendingen zien'), ('can_upload_nazendingen', 'Mag Nazendingen uploaden'), ('can_view_news', 'Mag Nieuws bekijken'), ('can_upload_news', 'Mag Nieuws uploaden'), ('can_view_policies', 'Mag Werkafspraken bekijken'), ('can_upload_werkafspraken', 'Mag Werkafspraken uploaden')]},
        ),
    ]
