# Generated by Django 5.2.7 on 2025-10-15 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_roster_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roster',
            options={'permissions': [('can_access_admin', 'Mag beheer openen'), ('can_manage_users', 'Mag gebruikers beheren'), ('can_view_roster', 'Mag rooster bekijken'), ('can_upload_roster', 'Mag roosters uploaden'), ('can_access_availability', 'Mag Beschikbaarheid openen'), ('can_view_av_medications', 'Mag subtab Geneesmiddelen zien'), ('can_upload_voorraad', 'Mag Voorraad uploaden'), ('can_view_av_nazendingen', 'Mag subtab Nazendingen zien'), ('can_upload_nazendingen', 'Mag Nazendingen uploaden'), ('can_view_news', 'Mag Nieuws bekijken'), ('can_upload_news', 'Mag Nieuws uploaden'), ('can_view_policies', 'Mag Werkafspraken bekijken'), ('can_upload_werkafspraken', 'Mag Werkafspraken uploaden'), ('can_send_beschikbaarheid', 'Mag Beschikbaarheid doorgeven'), ('can_view_beschikbaarheidsdashboard', 'Mag Beschikbaarheid Personeel bekijken')]},
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('morning', models.BooleanField(default=False)),
                ('afternoon', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
