# Generated by Django 5.2.7 on 2025-10-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_roster_options_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
