# Generated by Django 5.2.7 on 2025-10-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_webauthncredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushsubscription',
            name='device_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
