# Generated by Django 5.2.7 on 2025-10-24 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_pushsubscription_device_hash'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebAuthnCredential',
        ),
    ]
