# Generated by Django 5.2.7 on 2025-11-08 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_delete_webauthncredential'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roster',
            options={'permissions': [('can_access_admin', 'Mag beheer openen'), ('can_manage_users', 'Mag gebruikers beheren'), ('can_view_agenda', 'Mag agenda bekijken'), ('can_upload_agenda', 'Mag agenda uploaden'), ('can_view_roster', 'Mag rooster bekijken'), ('can_upload_roster', 'Mag roosters uploaden'), ('can_access_availability', 'Mag Beschikbaarheid openen'), ('can_view_av_medications', 'Mag subtab Geneesmiddelen zien'), ('can_upload_voorraad', 'Mag Voorraad uploaden'), ('can_view_av_nazendingen', 'Mag subtab Nazendingen zien'), ('can_upload_nazendingen', 'Mag Nazendingen uploaden'), ('can_view_news', 'Mag Nieuws bekijken'), ('can_upload_news', 'Mag Nieuws uploaden'), ('can_view_policies', 'Mag Werkafspraken bekijken'), ('can_upload_werkafspraken', 'Mag Werkafspraken uploaden'), ('can_send_beschikbaarheid', 'Mag Beschikbaarheid doorgeven'), ('can_view_beschikbaarheidsdashboard', 'Mag Beschikbaarheid Personeel bekijken'), ('can_view_medicatiebeoordeling', 'Mag Medicatiebeoordeling bekijken'), ('can_perform_medicatiebeoordeling', 'Mag Medicatiebeoordeling uitvoeren')]},
        ),
    ]
