# Generated by Django 5.2.7 on 2025-11-19 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_roster_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebAuthnPasskey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_id', models.CharField(help_text='Base64url-encoded credential.id', max_length=255, unique=True)),
                ('public_key', models.TextField(help_text='Base64url-encoded public key van de credential')),
                ('sign_count', models.BigIntegerField(default=0)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('device_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('label', models.CharField(blank=True, help_text="Bijv. 'iPhone van Jan'", max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passkeys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'device_hash', 'credential_id')},
            },
        ),
    ]
