# Generated by Django 5.2.7 on 2025-11-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_webauthnpasskey'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webauthnpasskey',
            options={'verbose_name': 'Passkey', 'verbose_name_plural': 'Passkeys'},
        ),
        migrations.RenameField(
            model_name='webauthnpasskey',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='webauthnpasskey',
            old_name='last_used',
            new_name='last_used_at',
        ),
        migrations.AlterUniqueTogether(
            name='webauthnpasskey',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='webauthnpasskey',
            name='backed_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='webauthnpasskey',
            name='nickname',
            field=models.CharField(blank=True, help_text="Bijvoorbeeld 'iPhone van Sem' of 'Werktelefoon'.", max_length=100),
        ),
        migrations.AddField(
            model_name='webauthnpasskey',
            name='transports',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='webauthnpasskey',
            name='user_handle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='webauthnpasskey',
            name='credential_id',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='webauthnpasskey',
            name='public_key',
            field=models.BinaryField(),
        ),
        migrations.RemoveField(
            model_name='webauthnpasskey',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='webauthnpasskey',
            name='label',
        ),
        migrations.RemoveField(
            model_name='webauthnpasskey',
            name='user_agent',
        ),
    ]
