# Generated by Django 5.2.7 on 2025-12-01 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_organization_userprofile_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Korte titel van het agendapunt (max. 100 tekens).', max_length=100, verbose_name='Titel')),
                ('description', models.CharField(help_text='Korte beschrijving (max. 500 tekens).', max_length=500, verbose_name='Beschrijving')),
                ('date', models.DateField(db_index=True, verbose_name='Datum')),
                ('category', models.CharField(choices=[('general', 'Algemeen'), ('outing', 'Uitje')], db_index=True, max_length=10, verbose_name='Categorie')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agenda_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'category', 'title'],
            },
        ),
    ]
