# Generated by Django 5.2.7 on 2025-12-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_agendaitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mailadres'),
        ),
        migrations.AddField(
            model_name='organization',
            name='email2',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mailadres 2'),
        ),
        migrations.AddField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefoonnummer'),
        ),
    ]
