# Generated by Django 5.2.7 on 2025-12-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_organization_email_organization_email2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mailadres'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='email2',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mailadres 2'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Telefoonnummer'),
            preserve_default=False,
        ),
    ]
