# Generated by Django 5.2.7 on 2025-12-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_newsitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='short_description',
            field=models.CharField(blank=True, help_text='Korte beschrijving voor in de lijst (max 200 tekens).', max_length=200),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
    ]
