# Generated by Django 5.2.7 on 2025-12-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_newsitem_short_description_alter_newsitem_file_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaitem',
            name='description',
            field=models.CharField(help_text='Korte beschrijving (max. 100 tekens).', max_length=100, verbose_name='Beschrijving'),
        ),
        migrations.AlterField(
            model_name='agendaitem',
            name='title',
            field=models.CharField(help_text='Korte titel van het agendapunt (max. 50 tekens).', max_length=50, verbose_name='Titel'),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='short_description',
            field=models.CharField(blank=True, help_text='Korte beschrijving voor in de lijst (max 100 tekens).', max_length=100),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
