# Generated by Django 5.2.7 on 2025-12-02 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_agendaitem_description_alter_agendaitem_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='file_path',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
