# Generated by Django 5.2.7 on 2025-12-03 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_newsitem_file_path'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roster',
            options={'permissions': [('can_access_admin', 'Mag beheer openen'), ('can_manage_users', 'Mag gebruikers beheren'), ('can_view_agenda', 'Mag agenda bekijken'), ('can_upload_agenda', 'Mag agenda uploaden'), ('can_view_roster', 'Mag rooster bekijken'), ('can_upload_roster', 'Mag roosters uploaden'), ('can_access_availability', 'Mag Beschikbaarheid openen'), ('can_view_av_medications', 'Mag subtab Geneesmiddelen zien'), ('can_upload_voorraad', 'Mag Voorraad uploaden'), ('can_view_av_nazendingen', 'Mag subtab Nazendingen zien'), ('can_upload_nazendingen', 'Mag Nazendingen uploaden'), ('can_view_news', 'Mag Nieuws bekijken'), ('can_upload_news', 'Mag Nieuws uploaden'), ('can_view_policies', 'Mag Werkafspraken bekijken'), ('can_upload_werkafspraken', 'Mag Werkafspraken uploaden'), ('can_send_beschikbaarheid', 'Mag Beschikbaarheid doorgeven'), ('can_view_beschikbaarheidsdashboard', 'Mag Beschikbaarheid Personeel bekijken'), ('can_view_medicatiebeoordeling', 'Mag Medicatiebeoordeling bekijken'), ('can_perform_medicatiebeoordeling', 'Mag Medicatiebeoordeling uitvoeren'), ('can_view_onboarding', 'Mag Onboarding openen'), ('can_view_personeel', 'Mag Personeel openen'), ('can_view_whoiswho', 'Mag Wie is wie? bekijken'), ('can_edit_whoiswho', 'Mag Wie is wie? aanpassen'), ('can_view_forms', 'Mag formulieren bekijken'), ('can_edit_forms', 'Mag formulieren aanpassen'), ('can_view_checklist', 'Mag checklist bekijken'), ('can_edit_checklist', 'Mag checklist aanpassen'), ('can_view_baxter', 'Mag Baxter openen'), ('can_view_baxter_omzettingslijst', 'Mag Baxter-omzettingslijst bekijken'), ('can_edit_baxter_omzettingslijst', 'Mag Baxter-omzettingslijst aanpassen'), ('can_view_baxter_no_delivery', "Mag 'Geen levering' bekijken"), ('can_edit_baxter_no_delivery', "Mag 'Geen levering' aanpassen"), ('can_view_baxter_sts_halfjes', 'Mag STS-halfjes bekijken'), ('can_edit_baxter_sts_halfjes', 'Mag STS-halfjes aanpassen'), ('can_view_baxter_laatste_potten', 'Mag laatste potten bekijken'), ('can_edit_baxter_laatste_potten', 'Mag laatste potten aanpassen'), ('can_view_openbare_apo', 'Mag Openbare apotheek-tegel zien'), ('can_view_instellings_apo', 'Mag Instellingsapotheek-tegel zien'), ('can_view_reviewplanner', 'Mag Review Planner bekijken'), ('can_edit_reviewplanner', 'Mag Review Planner bewerken'), ('can_view_portavita', 'Mag Portavita Check bekijken'), ('can_edit_portavita', 'Mag Portavita Check bewerken')]},
        ),
    ]
