# Generated by Django 5.2.7 on 2025-12-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_roster_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Werkafspraak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('short_description', models.CharField(blank=True, help_text='Korte beschrijving van de werkafspraak', max_length=100)),
                ('file_path', models.CharField(blank=True, default='', max_length=255)),
                ('file_hash', models.CharField(blank=True, db_index=True, max_length=32)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
