# Generated by Django 5.2.7 on 2025-12-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_werkafspraak'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='werkafspraak',
            options={},
        ),
        migrations.AddField(
            model_name='werkafspraak',
            name='category',
            field=models.CharField(choices=[('Baxterproductie', 'Baxterproductie'), ('Instellingsapotheek', 'Instellingsapotheek'), ('Openbare Apo', 'Openbare Apo')], default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='werkafspraak',
            name='short_description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='werkafspraak',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
