# Generated by Django 5.2.7 on 2025-12-03 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_werkafspraak_options_werkafspraak_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='werkafspraak',
            options={'ordering': ['category', 'title']},
        ),
        migrations.RenameField(
            model_name='werkafspraak',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='werkafspraak',
            name='file_hash',
        ),
        migrations.RemoveField(
            model_name='werkafspraak',
            name='original_filename',
        ),
        migrations.AddField(
            model_name='werkafspraak',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='werkafspraken', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='werkafspraak',
            name='category',
            field=models.CharField(choices=[('baxter', 'Baxterproductie'), ('instelling', 'Instellingenapotheek'), ('openbare', 'Openbare Apotheek')], db_index=True, max_length=10, verbose_name='Categorie'),
        ),
        migrations.AlterField(
            model_name='werkafspraak',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='werkafspraken/'),
        ),
        migrations.AlterField(
            model_name='werkafspraak',
            name='short_description',
            field=models.CharField(help_text='Korte beschrijving van de werkafspraak (max. 100 tekens).', max_length=100, verbose_name='Beschrijving'),
        ),
        migrations.AlterField(
            model_name='werkafspraak',
            name='title',
            field=models.CharField(help_text='Korte titel van de werkafspraak (max. 50 tekens).', max_length=50, verbose_name='Titel'),
        ),
    ]
