# Generated by Django 5.2.7 on 2025-12-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_werkafspraak_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='werkafspraak',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddField(
            model_name='werkafspraak',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='werkafspraak',
            name='file_path',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
