# Generated by Django 5.2.7 on 2025-12-05 15:06

import django.db.models.deletion
import fernet_fields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_werkafspraak_file_hash_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicatieReviewAfdeling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afdeling', models.CharField(max_length=255)),
                ('bron', models.CharField(default='medimo', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='afdelingen_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='afdelingen_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medicatiereview Afdeling',
                'verbose_name_plural': 'Medicatiereview Afdelingen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicatieReviewPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', fernet_fields.fields.EncryptedCharField(max_length=255)),
                ('geboortedatum', fernet_fields.fields.EncryptedDateField(blank=True, null=True)),
                ('analysis_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('afdeling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patienten', to='core.medicatiereviewafdeling')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patienten_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patienten_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medicatiereview Patiënt',
                'verbose_name_plural': 'Medicatiereview Patiënten',
            },
        ),
        migrations.CreateModel(
            name='MedicatieReviewComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jansen_group_id', models.IntegerField()),
                ('tekst', fernet_fields.fields.EncryptedTextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.medicatiereviewpatient')),
            ],
            options={
                'unique_together': {('patient', 'jansen_group_id')},
            },
        ),
    ]
