# Generated by Django 5.2.7 on 2025-12-04 14:53

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_werkafspraak_file_hash_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicatieReviewAfdeling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afdeling', models.CharField(max_length=255)),
                ('bron', models.CharField(default='medimo', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medicatiereview Afdeling',
                'verbose_name_plural': 'Medicatiereview Afdelingen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicatieReviewPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=255)),
                ('leeftijd', models.IntegerField(blank=True, null=True)),
                ('analysis_data', core.models.EncryptedJSONField()),
                ('afdeling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patienten', to='core.medicatiereviewafdeling')),
            ],
            options={
                'ordering': ['naam'],
            },
        ),
        migrations.CreateModel(
            name='MedicatieReviewComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jansen_group_id', models.IntegerField()),
                ('tekst', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.medicatiereviewpatient')),
            ],
            options={
                'unique_together': {('patient', 'jansen_group_id')},
            },
        ),
    ]
