# Generated by Django 5.2.7 on 2025-12-06 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_medicatiereviewafdeling_medicatiereviewpatient_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicatiereviewafdeling',
            options={'ordering': ['organisatie__name', 'afdeling'], 'verbose_name': 'Medicatiereview Afdeling', 'verbose_name_plural': 'Medicatiereview Afdelingen'},
        ),
        migrations.RemoveField(
            model_name='medicatiereviewafdeling',
            name='bron',
        ),
        migrations.AddField(
            model_name='medicatiereviewafdeling',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mailadres'),
        ),
        migrations.AddField(
            model_name='medicatiereviewafdeling',
            name='email2',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mailadres 2'),
        ),
        migrations.AddField(
            model_name='medicatiereviewafdeling',
            name='locatie',
            field=models.CharField(default=1, max_length=255, verbose_name='Locatie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicatiereviewafdeling',
            name='organisatie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='medicatie_afdelingen', to='core.organization', verbose_name='Organisatie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicatiereviewafdeling',
            name='telefoon',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telefoonnummer'),
        ),
        migrations.AlterField(
            model_name='medicatiereviewafdeling',
            name='afdeling',
            field=models.CharField(max_length=255, verbose_name='Naam afdeling'),
        ),
    ]
