# Generated by Django 5.2.7 on 2025-12-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_medicatiereviewafdeling_medicatiereviewpatient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicatiereviewpatient',
            name='leeftijd',
        ),
        migrations.AddField(
            model_name='medicatiereviewpatient',
            name='geboortedatum',
            field=models.DateField(blank=True, null=True),
        ),
    ]
