# Generated by Django 5.2.7 on 2025-12-06 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_medicatiereviewafdeling_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='medicatiereviewafdeling',
            unique_together={('organisatie', 'afdeling')},
        ),
    ]
