# Generated by Django 5.2.7 on 2025-12-07 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_medicatiereviewafdeling_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='medicatiereviewafdeling',
            unique_together={('organisatie', 'locatie', 'afdeling')},
        ),
    ]
