# Generated by Django 5.2.7 on 2025-12-07 13:49

import fernet_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_medicatiereviewafdeling_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicatiereviewcomment',
            name='historie',
            field=fernet_fields.fields.EncryptedTextField(blank=True),
        ),
    ]
