# Generated by Django 5.2.7 on 2025-12-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_medicatiereviewcomment_historie'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='org_type',
            field=models.CharField(choices=[('apotheek', 'Apotheek'), ('zorginstelling', 'Zorginstelling')], default='apotheek', max_length=20, verbose_name='Type organisatie'),
        ),
    ]
