# Generated by Django 5.2.7 on 2025-12-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_organization_org_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoorraadItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zi_nummer', models.CharField(max_length=8, unique=True)),
                ('naam', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Voorraaditem',
                'verbose_name_plural': 'Voorraad',
                'ordering': ['naam'],
            },
        ),
    ]
