# Generated by Django 5.2.7 on 2025-12-15 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_voorraaditem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voorraaditem',
            name='id',
        ),
        migrations.AlterField(
            model_name='voorraaditem',
            name='zi_nummer',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Nazending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(verbose_name='Datum nazending')),
                ('nazending_tot', models.CharField(help_text="Bijv. week 45 of 'onbekend'", max_length=255, verbose_name='Nazending tot')),
                ('alternatief', models.CharField(blank=True, help_text='Vrij tekstveld', max_length=255, verbose_name='Alternatief')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voorraad_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nazendingen', to='core.voorraaditem', verbose_name='Geneesmiddel')),
            ],
            options={
                'verbose_name': 'Nazending',
                'verbose_name_plural': 'Nazendingen',
                'ordering': ['datum', 'created_at'],
            },
        ),
    ]
