# Generated by Django 5.2.7 on 2025-12-17 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0039_alter_roster_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandaardInlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standaard_rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='standaard_inlog_config', to='auth.group', verbose_name='Standaard Rol')),
            ],
        ),
    ]
