# Generated by Django 5.2.7 on 2025-12-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_standaardinlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicatiereviewafdeling',
            name='code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Code'),
        ),
    ]
