# Generated by Django 5.2.7 on 2025-12-26 13:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_roster_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaatstePot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(default=django.utils.timezone.now, verbose_name='Datum melding')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('voorraad_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laatste_potten', to='core.voorraaditem', verbose_name='Geneesmiddel')),
            ],
            options={
                'verbose_name': 'Laatste Pot',
                'verbose_name_plural': 'Laatste Potten',
                'ordering': ['-datum', '-created_at'],
            },
        ),
    ]
