# Generated by Django 5.2.7 on 2025-12-26 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_laatstepot'),
    ]

    operations = [
        migrations.CreateModel(
            name='STSHalfje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item_alternatief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sts_alternatieven', to='core.voorraaditem', verbose_name='Alternatieve sterkte')),
                ('item_gehalveerd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sts_gehalveerd', to='core.voorraaditem', verbose_name='Geneesmiddel dat gehalveerd wordt')),
            ],
            options={
                'verbose_name': 'STS Halfje',
                'verbose_name_plural': 'STS Halfjes',
                'ordering': ['-created_at'],
            },
        ),
    ]
