# Generated by Django 5.2.7 on 2025-12-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_alter_roster_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='evening',
            field=models.BooleanField(default=False),
        ),
    ]
