# Generated by Django 5.2.7 on 2025-12-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_location_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='status',
            field=models.CharField(choices=[('concept', 'Concept'), ('accepted', 'Accepted')], db_index=True, default='concept', max_length=20),
        ),
        migrations.AddField(
            model_name='shift',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='period',
            field=models.CharField(choices=[('morning', 'Ochtend'), ('afternoon', 'Middag'), ('evening', 'Avond')], db_index=True, max_length=10),
        ),
    ]
