# Generated by Django 5.2.7 on 2025-12-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_task_min_fri_afternoon_task_min_fri_evening_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dienstverband',
            field=models.CharField(choices=[('vast', 'Vast contract'), ('oproep', 'Oproeper')], db_index=True, default='oproep', max_length=10, verbose_name='Dienstverband'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_fri_am',
            field=models.BooleanField(default=False, verbose_name='Vr ochtend'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_fri_pm',
            field=models.BooleanField(default=False, verbose_name='Vr middag'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_mon_am',
            field=models.BooleanField(default=False, verbose_name='Ma ochtend'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_mon_pm',
            field=models.BooleanField(default=False, verbose_name='Ma middag'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_thu_am',
            field=models.BooleanField(default=False, verbose_name='Do ochtend'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_thu_pm',
            field=models.BooleanField(default=False, verbose_name='Do middag'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_tue_am',
            field=models.BooleanField(default=False, verbose_name='Di ochtend'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_tue_pm',
            field=models.BooleanField(default=False, verbose_name='Di middag'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_wed_am',
            field=models.BooleanField(default=False, verbose_name='Wo ochtend'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_wed_pm',
            field=models.BooleanField(default=False, verbose_name='Wo middag'),
        ),
    ]
