# Generated by Django 5.2.7 on 2025-12-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_userprofile_dienstverband_userprofile_work_fri_am_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RosterWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday', models.DateField(db_index=True, unique=True)),
                ('week_slug', models.CharField(db_index=True, max_length=16)),
                ('file_path', models.CharField(blank=True, default='', max_length=255)),
                ('file_hash', models.CharField(blank=True, db_index=True, max_length=32)),
                ('n_pages', models.PositiveIntegerField(default=0)),
                ('preview_ext', models.CharField(default='webp', max_length=8)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-monday'],
            },
        ),
    ]
