# Generated by Django 5.2.7 on 2026-01-01 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_rosterweek'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='status',
        ),
        migrations.CreateModel(
            name='ShiftDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('period', models.CharField(choices=[('morning', 'Ochtend'), ('afternoon', 'Middag'), ('evening', 'Avond')], db_index=True, max_length=10)),
                ('action', models.CharField(choices=[('upsert', 'Upsert'), ('delete', 'Delete')], db_index=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shift_drafts', to='core.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'period'],
                'unique_together': {('user', 'date', 'period')},
            },
        ),
    ]
