# Generated by Django 5.2.7 on 2026-01-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_remove_shift_status_shiftdraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='color',
            field=models.CharField(choices=[('green', 'Groen'), ('red', 'Rood'), ('blue', 'Blauw')], default='blue', max_length=10),
        ),
    ]
