# Generated by Django 5.2.7 on 2026-01-03 22:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_location_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='calendar_token',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
