# Generated by Django 5.2.7 on 2026-01-03 22:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_dedupe_calendar_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='calendar_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
