# Generated by Django 5.2.7 on 2026-01-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_location_deleted_at_location_is_active_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('location', 'name'), name='uniq_active_task_name_per_location'),
        ),
    ]
