# Generated by Django 5.2.7 on 2026-01-06 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_task_uniq_active_task_name_per_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='source',
            field=models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual')], db_index=True, default='manual', max_length=10),
        ),
    ]
