# Generated by Django 5.2.7 on 2026-01-07 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_availability_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingFormulier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Naam van het formulier (max. 80 tekens).', max_length=80, verbose_name='Titel')),
                ('url', models.URLField(help_text='Volledige link naar het formulier (bijv. Google Forms).', max_length=500, verbose_name='URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formulieren', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
                'permissions': [('can_view_forms', 'Mag formulieren bekijken'), ('can_edit_forms', 'Mag formulieren aanpassen')],
            },
        ),
    ]
