# Generated by Django 5.2.7 on 2026-01-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_inschrijvingitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inschrijvingitem',
            options={'ordering': ['verloopdatum', 'title']},
        ),
        migrations.AddField(
            model_name='inschrijvingitem',
            name='verloopdatum',
            field=models.DateField(blank=True, help_text='Optioneel: na deze datum wordt dit item automatisch verwijderd.', null=True, verbose_name='Verloopdatum'),
        ),
    ]
