# Generated by Django 5.2.7 on 2026-01-08 19:44

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_alter_roster_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UrenDoorgevenSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evening_allowance_pct', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Bijv. 25.00 voor 25% toeslag.', max_digits=5, verbose_name='CAO toeslag % na 18:00')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='urendoorgeven_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UrenInvoer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(db_index=True, help_text='Eerste dag van de maand.', verbose_name='Maand')),
                ('hours_before_18', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, verbose_name='Uren tot 18:00')),
                ('hours_after_18', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, verbose_name='Uren na 18:00')),
                ('evening_allowance_pct_used', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Snapshot van de instelling op moment van opslaan.', max_digits=5, verbose_name='Toeslag % gebruikt')),
                ('submitted_at', models.DateTimeField(auto_now=True, verbose_name='Ingediend op')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uren_invoer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month', 'user_id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'month'), name='uniq_user_month_ureninvoer')],
            },
        ),
    ]
