# Generated by Django 5.2.7 on 2026-01-10 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_urendoorgevensettings_ureninvoer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Profielfoto'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar_hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='NotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('push_enabled', models.BooleanField(default=True)),
                ('push_new_roster', models.BooleanField(default=True)),
                ('push_new_agenda', models.BooleanField(default=True)),
                ('push_news_upload', models.BooleanField(default=True)),
                ('push_dienst_changed', models.BooleanField(default=True)),
                ('push_birthday_self', models.BooleanField(default=True)),
                ('push_birthday_apojansen', models.BooleanField(default=True)),
                ('push_uren_reminder', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('email_birthday_self', models.BooleanField(default=True)),
                ('email_uren_reminder', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notif_prefs', to='core.userprofile')),
            ],
        ),
    ]
