# Generated by Django 5.2.7 on 2026-01-10 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_alter_roster_options_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='function',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='core.function'),
        ),
    ]
