# Generated by Django 5.2.7 on 2026-01-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_userprofile_function'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreferences',
            name='email_diensten_overzicht',
            field=models.BooleanField(default=True),
        ),
    ]
