# Generated by Django 5.2.7 on 2026-01-11 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_alter_roster_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='Telefoonnummer'),
        ),
    ]
