# Generated by Django 5.2.7 on 2026-01-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_alter_roster_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=512)),
                ('category', models.CharField(choices=[('preparaat', 'Preparaat'), ('groep', 'Groep'), ('indicatie', 'Indicatie')], max_length=20)),
                ('content_hash', models.CharField(max_length=64)),
                ('last_scraped', models.DateTimeField(auto_now=True)),
                ('gcs_path', models.CharField(blank=True, max_length=1024)),
            ],
        ),
    ]
