# Generated by Django 5.2.7 on 2026-01-13 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_scrapedpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='stshalfje',
            name='apotheek',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sts_halfjes', to='core.organization', verbose_name='Apotheek'),
        ),
        migrations.AddField(
            model_name='stshalfje',
            name='patient_geboortedatum',
            field=models.DateField(blank=True, null=True, verbose_name='Geboortedatum patiënt'),
        ),
        migrations.AddField(
            model_name='stshalfje',
            name='patient_naam',
            field=models.CharField(blank=True, max_length=255, verbose_name='Patiënt'),
        ),
    ]
