# Generated by Django 5.2.7 on 2026-01-13 16:42

import fernet_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_stshalfje_apotheek_stshalfje_patient_geboortedatum_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stshalfje',
            name='patient_geboortedatum',
        ),
        migrations.RemoveField(
            model_name='stshalfje',
            name='patient_naam',
        ),
        migrations.AddField(
            model_name='stshalfje',
            name='patient_geboortedatum_enc',
            field=fernet_fields.fields.EncryptedDateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stshalfje',
            name='patient_naam_enc',
            field=fernet_fields.fields.EncryptedCharField(blank=True, default='', max_length=255),
        ),
    ]
