# Generated by Django 5.2.7 on 2026-01-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_alter_roster_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaitem',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Eindtijd'),
        ),
        migrations.AddField(
            model_name='agendaitem',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Starttijd'),
        ),
    ]
