# Generated by Django 5.2.7 on 2026-01-14 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_agendaitem_end_time_agendaitem_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='laatstepot',
            name='afhandeling',
            field=models.TextField(blank=True, default='', help_text='Vrije tekst: hoe is dit afgehandeld?', verbose_name='Afhandeling'),
        ),
    ]
