# Generated by Django 5.2.7 on 2026-01-14 13:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_laatstepot_afhandeling'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dagdeel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('morning', 'Ochtend'), ('afternoon', 'Middag'), ('evening', 'Avond')], db_index=True, max_length=12, unique=True)),
                ('name', models.CharField(default='', editable=False, max_length=40)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('allowance_pct', models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0)])),
                ('sort_order', models.PositiveSmallIntegerField(default=0, editable=False)),
            ],
            options={
                'ordering': ['sort_order'],
                'constraints': [models.CheckConstraint(condition=models.Q(('allowance_pct__gte', 0), ('allowance_pct__lte', 300)), name='dagdeel_allowance_pct_range_0_300')],
            },
        ),
    ]
