# Generated by Django 5.2.7 on 2026-01-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_dagdeel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dagdeel',
            name='code',
            field=models.CharField(choices=[('morning', 'Ochtend'), ('afternoon', 'Middag'), ('pre_evening', 'Vooravond'), ('evening', 'Avond'), ('night', 'Nacht')], db_index=True, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='dagdeel',
            name='name',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='dagdeel',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
