# Generated by Django 5.2.7 on 2026-01-14 14:30
from datetime import time
from django.db import migrations


def seed_dagdelen(apps, schema_editor):
    Dagdeel = apps.get_model("core", "Dagdeel")

    # defaults bij create (je kunt allowance_pct aanpassen)
    defaults = [
        ("morning",      time(9, 0),  time(13, 0), 100, "Ochtend",   10),
        ("afternoon",    time(13, 0), time(17, 0), 100, "Middag",    20),
        ("pre_evening",  time(18, 0), time(20, 0), 100, "Vooravond", 30),
        ("evening",      time(20, 0), time(0, 0),  120, "Avond",     40),
        ("night",        time(0, 0),  time(7, 0),  140, "Nacht",     50),
    ]

    wanted_codes = [c for (c, *_rest) in defaults]

    # 1) bestaande ophalen
    existing = Dagdeel.objects.in_bulk(wanted_codes, field_name="code")

    to_create = []
    to_update = []

    for code, start, end, pct, label, order in defaults:
        obj = existing.get(code)
        if obj is None:
            # alleen defaults bij create
            to_create.append(
                Dagdeel(
                    code=code,
                    start_time=start,
                    end_time=end,
                    allowance_pct=pct,
                    name=label,
                    sort_order=order,
                )
            )
        else:
            # name + sort_order altijd vastzetten (volgorde/labels)
            changed = False
            if obj.name != label:
                obj.name = label
                changed = True
            if obj.sort_order != order:
                obj.sort_order = order
                changed = True
            if changed:
                to_update.append(obj)

    # 2) writes (bulk)
    if to_create:
        Dagdeel.objects.bulk_create(to_create)

    if to_update:
        Dagdeel.objects.bulk_update(to_update, ["name", "sort_order"])


def unseed_dagdelen(apps, schema_editor):
    Dagdeel = apps.get_model("core", "Dagdeel")
    Dagdeel.objects.filter(
        code__in=["morning", "afternoon", "pre_evening", "evening", "night"]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0087_alter_dagdeel_code_alter_dagdeel_name_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_dagdelen, reverse_code=unseed_dagdelen),
    ]
