# Generated by Django 5.2.7 on 2026-01-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_seed_dagdelen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='afternoon',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='evening',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='morning',
        ),
        migrations.AddField(
            model_name='availability',
            name='dagdelen',
            field=models.ManyToManyField(blank=True, limit_choices_to={'code__in': ('morning', 'afternoon', 'pre_evening')}, related_name='availabilities', to='core.dagdeel'),
        ),
    ]
