# Generated by Django 5.2.7 on 2026-01-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_remove_availability_afternoon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='work_fri_ev',
            field=models.BooleanField(default=False, verbose_name='Vr vooravond'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_mon_ev',
            field=models.BooleanField(default=False, verbose_name='Ma vooravond'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_sat_am',
            field=models.BooleanField(default=False, verbose_name='Za ochtend'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_sat_ev',
            field=models.BooleanField(default=False, verbose_name='Za vooravond'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_sat_pm',
            field=models.BooleanField(default=False, verbose_name='Za middag'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_thu_ev',
            field=models.BooleanField(default=False, verbose_name='Do vooravond'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_tue_ev',
            field=models.BooleanField(default=False, verbose_name='Di vooravond'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='work_wed_ev',
            field=models.BooleanField(default=False, verbose_name='Wo vooravond'),
        ),
    ]
