# Generated by Django 5.2.7 on 2026-01-20 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_userprofile_work_fri_ev_userprofile_work_mon_ev_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ureninvoer',
            name='user',
        ),
        migrations.CreateModel(
            name='UrenMaand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(db_index=True, help_text='Eerste dag van de maand.', verbose_name='Maand')),
                ('kilometers', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uren_maanden', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-month', 'user_id'],
            },
        ),
        migrations.CreateModel(
            name='UrenRegel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(db_index=True, help_text='Eerste dag van de actieve maand.')),
                ('date', models.DateField(db_index=True)),
                ('source', models.CharField(choices=[('shift', 'Shift'), ('manual', 'Manual')], db_index=True, default='manual', max_length=10)),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=5, null=True, verbose_name='Gewerkte uren')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dagdeel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uren_regels', to='core.dagdeel')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uren_regels', to='core.shift')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uren_regels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'dagdeel__sort_order', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='UrenDoorgevenSettings',
        ),
        migrations.DeleteModel(
            name='UrenInvoer',
        ),
        migrations.AddConstraint(
            model_name='urenmaand',
            constraint=models.UniqueConstraint(fields=('user', 'month'), name='uniq_user_month_urenmaand'),
        ),
        migrations.AddConstraint(
            model_name='urenregel',
            constraint=models.UniqueConstraint(fields=('user', 'date', 'dagdeel'), name='uniq_user_date_dagdeel_urenregel'),
        ),
    ]
