# Generated by Django 5.2.7 on 2026-01-22 11:16

import django.db.models.deletion
import fernet_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_remove_ureninvoer_user_urenmaand_urenregel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoDeliveryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jaar', models.PositiveIntegerField(verbose_name='Jaar')),
                ('week', models.PositiveIntegerField(verbose_name='Week')),
                ('dag', models.DateField(verbose_name='Dag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apotheek', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='no_delivery_lists', to='core.organization', verbose_name='Apotheek')),
            ],
            options={
                'verbose_name': 'Geen levering lijst',
                'verbose_name_plural': 'Geen levering lijsten',
                'ordering': ['-dag', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NoDeliveryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afdeling', models.CharField(blank=True, default='', max_length=255, verbose_name='Afdeling')),
                ('patient_naam_enc', fernet_fields.fields.EncryptedCharField(blank=True, default='', max_length=255)),
                ('patient_geboortedatum_enc', fernet_fields.fields.EncryptedDateField(blank=True, null=True)),
                ('vanaf_datum', models.DateField(blank=True, null=True, verbose_name='Vanaf datum')),
                ('sts_paraaf', models.CharField(blank=True, default='', max_length=64, verbose_name='STS paraaf')),
                ('roller_paraaf', models.CharField(blank=True, default='', max_length=64, verbose_name='Roller paraaf')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gevraagd_geneesmiddel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='no_delivery_entries', to='core.voorraaditem', verbose_name='Gevraagd geneesmiddel')),
                ('no_delivery_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.nodeliverylist', verbose_name='Geen levering lijst')),
            ],
            options={
                'verbose_name': 'Geen levering entry',
                'verbose_name_plural': 'Geen levering entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='nodeliverylist',
            constraint=models.UniqueConstraint(fields=('apotheek', 'jaar', 'week', 'dag'), name='uniq_no_delivery_list_apotheek_jaar_week_dag'),
        ),
    ]
