# Generated by Django 5.2.7 on 2026-01-22 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_nodeliverylist_nodeliveryentry_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nodeliverylist',
            options={'ordering': ['-created_at'], 'verbose_name': 'Geen levering lijst', 'verbose_name_plural': 'Geen levering lijsten'},
        ),
        migrations.RemoveConstraint(
            model_name='nodeliverylist',
            name='uniq_no_delivery_list_apotheek_jaar_week_dag',
        ),
        migrations.AlterField(
            model_name='nodeliveryentry',
            name='roller_paraaf',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Roller paraaf'),
        ),
        migrations.AlterField(
            model_name='nodeliveryentry',
            name='sts_paraaf',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='STS paraaf'),
        ),
        migrations.AlterField(
            model_name='nodeliverylist',
            name='dag',
            field=models.CharField(choices=[('MA', 'Maandag'), ('DI', 'Dinsdag'), ('WO', 'Woensdag'), ('DO', 'Donderdag'), ('VR', 'Vrijdag'), ('ZA', 'Zaterdag')], default='MA', max_length=2, verbose_name='Dag'),
        ),
        migrations.AlterField(
            model_name='nodeliverylist',
            name='jaar',
            field=models.IntegerField(verbose_name='Jaar'),
        ),
        migrations.AlterField(
            model_name='nodeliverylist',
            name='week',
            field=models.IntegerField(verbose_name='Week'),
        ),
        migrations.AlterUniqueTogether(
            name='nodeliverylist',
            unique_together={('apotheek', 'jaar', 'week', 'dag')},
        ),
    ]
