# Generated by Django 5.2.7 on 2026-01-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_alter_nodeliverylist_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nodeliveryentry',
            options={'ordering': ['-updated_at', '-created_at'], 'verbose_name': 'Geen levering entry', 'verbose_name_plural': 'Geen levering entries'},
        ),
        migrations.AlterModelOptions(
            name='nodeliverylist',
            options={'ordering': ['-updated_at', '-created_at'], 'verbose_name': 'Geen levering lijst', 'verbose_name_plural': 'Geen levering lijsten'},
        ),
        migrations.AddField(
            model_name='nodeliveryentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='nodeliverylist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='nodeliveryentry',
            name='afdeling',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Afdeling'),
        ),
    ]
