# Generated by Django 5.2.7 on 2026-01-23 11:24

import django.db.models.deletion
import fernet_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_alter_roster_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roster',
            options={'permissions': [('can_access_admin', 'Mag beheer openen'), ('can_access_profiel', 'Mag profiel aanpassen'), ('can_manage_users', 'Mag gebruikers beheren'), ('can_manage_groups', 'Mag groepen beheren'), ('can_manage_afdelingen', 'Mag afdelingen beheren'), ('can_manage_orgs', 'Mag organisaties beheren'), ('can_manage_tasks', 'Mag taken beheren'), ('can_manage_functies', 'Mag functies beheren'), ('can_manage_bezorgen', 'Mag bezorgen beheren'), ('can_view_agenda', 'Mag agenda bekijken'), ('can_upload_agenda', 'Mag agenda uploaden'), ('can_view_roster', 'Mag rooster bekijken'), ('can_upload_roster', 'Mag roosters uploaden'), ('can_access_availability', 'Mag Beschikbaarheid openen'), ('can_view_av_medications', 'Mag subtab Geneesmiddelen zien'), ('can_upload_voorraad', 'Mag Voorraad uploaden'), ('can_view_av_nazendingen', 'Mag subtab Nazendingen zien'), ('can_upload_nazendingen', 'Mag Nazendingen uploaden'), ('can_view_news', 'Mag Nieuws bekijken'), ('can_upload_news', 'Mag Nieuws uploaden'), ('can_view_policies', 'Mag Werkafspraken bekijken'), ('can_upload_werkafspraken', 'Mag Werkafspraken uploaden'), ('can_send_beschikbaarheid', 'Mag Beschikbaarheid doorgeven'), ('can_view_beschikbaarheidsdashboard', 'Mag Beschikbaarheid Personeel bekijken'), ('can_edit_beschikbaarheidsdashboard', 'Mag diensten toewijzen'), ('can_view_medicatiebeoordeling', 'Mag Medicatiebeoordeling bekijken'), ('can_perform_medicatiebeoordeling', 'Mag Medicatiebeoordeling uitvoeren'), ('can_view_onboarding', 'Mag Onboarding openen'), ('can_view_personeel', 'Mag Personeel openen'), ('can_view_diensten', 'Mag Diensten bekijken'), ('can_view_urendoorgeven', 'Mag uren doorgeven bekijken'), ('can_edit_urendoorgeven', 'Mag uren toeslag aanpassen'), ('can_view_ziekmelden', 'Mag Ziek Melden bekijken'), ('can_edit_ziekmelden', 'Mag personeel ziek melden'), ('can_view_inschrijven', 'Mag zich inschrijven'), ('can_edit_inschrijven', 'Mag inschrijving formulieren aanpassen'), ('can_view_whoiswho', 'Mag Wie is wie? bekijken'), ('can_edit_whoiswho', 'Mag Wie is wie? aanpassen'), ('can_view_forms', 'Mag formulieren bekijken'), ('can_edit_forms', 'Mag formulieren aanpassen'), ('can_view_checklist', 'Mag checklist bekijken'), ('can_edit_checklist', 'Mag checklist aanpassen'), ('can_view_baxter', 'Mag Baxter openen'), ('can_view_baxter_omzettingslijst', 'Mag Baxter-omzettingslijst bekijken'), ('can_edit_baxter_omzettingslijst', 'Mag Baxter-omzettingslijst aanpassen'), ('can_send_baxter_omzettingslijst', 'Mag Baxter-omzettingslijst versturen'), ('can_view_baxter_no_delivery', "Mag 'Geen levering' bekijken"), ('can_edit_baxter_no_delivery', "Mag 'Geen levering' aanpassen"), ('can_send_baxter_no_delivery', "Mag 'Geen levering' versturen"), ('can_view_baxter_sts_halfjes', 'Mag STS-halfjes bekijken'), ('can_edit_baxter_sts_halfjes', 'Mag STS-halfjes aanpassen'), ('can_send_baxter_sts_halfjes', 'Mag STS-halfjes versturen'), ('can_view_baxter_laatste_potten', 'Mag laatste potten bekijken'), ('can_edit_baxter_laatste_potten', 'Mag laatste potten aanpassen'), ('can_perform_bestellingen', 'Krijgt een melding bij aanpassing laatste potten'), ('can_view_openbare_apo', 'Mag Openbare apotheek-tegel zien'), ('can_view_instellings_apo', 'Mag Instellingsapotheek-tegel zien'), ('can_view_reviewplanner', 'Mag Review Planner bekijken'), ('can_edit_reviewplanner', 'Mag Review Planner bewerken'), ('can_view_portavita', 'Mag Portavita Check bekijken'), ('can_edit_portavita', 'Mag Portavita Check bewerken'), ('can_view_bezorgers', 'Mag Bezorgers openen'), ('can_view_bakkenbezorgen', 'Mag bakken bezorgen'), ('can_view_afleverstatus', 'Mag afleverstatus bekijken'), ('can_view_kompasgpt', 'Mag KompasGPT gebruiken')]},
        ),
        migrations.CreateModel(
            name='Omzettingslijst',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jaar', models.IntegerField(verbose_name='Jaar')),
                ('week', models.IntegerField(verbose_name='Week')),
                ('dag', models.CharField(choices=[('MA', 'Maandag'), ('DI', 'Dinsdag'), ('WO', 'Woensdag'), ('DO', 'Donderdag'), ('VR', 'Vrijdag'), ('ZA', 'Zaterdag')], default='MA', max_length=2, verbose_name='Dag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apotheek', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='omzettingslijsten', to='core.organization', verbose_name='Apotheek')),
            ],
            options={
                'verbose_name': 'Omzettingslijst',
                'verbose_name_plural': 'Omzettingslijsten',
                'ordering': ['-updated_at', '-created_at'],
                'unique_together': {('apotheek', 'jaar', 'week', 'dag')},
            },
        ),
        migrations.CreateModel(
            name='OmzettingslijstEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afdeling', models.CharField(blank=True, default='', max_length=10, verbose_name='Afdeling')),
                ('patient_naam_enc', fernet_fields.fields.EncryptedCharField(blank=True, default='', max_length=255)),
                ('patient_geboortedatum_enc', fernet_fields.fields.EncryptedDateField(blank=True, null=True)),
                ('omschrijving_geneesmiddel', models.CharField(blank=True, default='', help_text='Bijv: tabl. rond wit 500', max_length=80, verbose_name='Omschrijving geneesmiddel')),
                ('vanaf_datum', models.DateField(blank=True, null=True, verbose_name='Vanaf datum')),
                ('sts_paraaf', models.CharField(blank=True, default='', max_length=50, verbose_name='STS paraaf')),
                ('roller_paraaf', models.CharField(blank=True, default='', max_length=50, verbose_name='Roller paraaf')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('geleverd_geneesmiddel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='omzettingslijst_entries_geleverd', to='core.voorraaditem', verbose_name='Geleverd geneesmiddel')),
                ('gevraagd_geneesmiddel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='omzettingslijst_entries_gevraagd', to='core.voorraaditem', verbose_name='Gevraagd geneesmiddel')),
                ('omzettingslijst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.omzettingslijst', verbose_name='Omzettingslijst')),
            ],
            options={
                'verbose_name': 'Omzettingslijst entry',
                'verbose_name_plural': 'Omzettingslijst entries',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
    ]
