# Generated by Django 5.2.7 on 2026-01-25 14:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_alter_roster_options_omzettingslijst_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NativePushToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=512, unique=True)),
                ('platform', models.CharField(blank=True, choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web'), ('', 'Unknown')], default='', max_length=20)),
                ('device_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='native_push_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
