# Generated by Django 5.2.7 on 2026-01-26 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_nativepushtoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NativeBiometricDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=128)),
                ('nickname', models.CharField(blank=True, max_length=100)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('other', 'Other')], default='other', max_length=20)),
                ('secret_hash', models.CharField(max_length=128)),
                ('secret_version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='native_biometric_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Native biometric device',
                'verbose_name_plural': 'Native biometric devices',
                'indexes': [models.Index(fields=['device_id'], name='core_native_device__fc7674_idx'), models.Index(fields=['user', 'device_id'], name='core_native_user_id_0eeb46_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'device_id'), name='uniq_user_device_id')],
            },
        ),
    ]
