# Generated by Django 5.2.7 on 2026-01-29 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_medicatiereviewmedgroupoverride'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicatiereviewmedgroupoverride',
            name='target_jansen_group_id',
            field=models.IntegerField(choices=[(1, 'Vallen?'), (2, 'Malen?'), (3, 'CVRM'), (4, 'Bloedstolling'), (5, 'Diabetes'), (6, 'Jicht'), (7, 'Valpreventie'), (8, 'Pijn'), (9, 'Psychofarmaca'), (10, 'Parkinson'), (11, 'Spierrelaxantia'), (12, 'Anemie'), (13, 'Astma/Copd'), (14, 'Allergie'), (15, 'Hoest'), (16, 'Antibiotica'), (17, 'Antimycotica'), (18, 'Antimycobacteriele middelen'), (19, 'Antivirale middelen'), (20, 'Hypofyse- en hypothalamus en verwante verbindingen'), (21, 'Schildklierhormonen'), (22, 'Corticosteroiden systemisch'), (23, 'Hormonen'), (24, 'Maag/darm'), (25, 'Lever'), (26, 'Calciumregulerende middelen'), (27, 'Pancreashormonen'), (28, 'Huid'), (29, 'Urogenitaal'), (30, 'RLS'), (31, 'Ogen'), (32, 'Neus'), (33, 'Mond'), (34, 'Oren'), (35, 'Vaccins'), (36, 'Sera en immunoglobulinen'), (37, 'Oncolytica'), (38, 'Reuma'), (39, 'Immunostimulantia'), (40, 'Immunosuppressiva'), (41, 'Anabolen'), (42, 'Wormen'), (43, 'Overig')]),
        ),
        migrations.AlterField(
            model_name='medicatiereviewmedgroupoverride',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
