# Generated by Django 5.2.7 on 2026-01-29 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_alter_medicatiereviewmedgroupoverride_target_jansen_group_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicatiereviewmedgroupoverride',
            name='override_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
