# Generated by Django 5.2.7 on 2026-02-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_stshalfje_afdeling_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='haptics_enabled',
            field=models.BooleanField(default=True, verbose_name='Haptic feedback'),
        ),
    ]
