# Generated by Django 5.2.7 on 2026-02-06 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_userprofile_haptics_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewPlanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('prep', 'In voorbereiding'), ('sent', 'Verstuurd'), ('done', 'Uitgevoerd')], default='prep', max_length=10)),
                ('arts', models.CharField(blank=True, max_length=255)),
                ('tijd', models.TimeField(blank=True, null=True)),
                ('bijzonderheden', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('afdeling', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewplanner_items', to='core.medicatiereviewafdeling')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewplanner_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewplanner_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review planner',
                'verbose_name_plural': 'Review planner',
                'ordering': ['-datum', '-updated_at'],
            },
        ),
    ]
