# Generated by Django 5.2.7 on 2026-02-11 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_reviewplanner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewplanner',
            name='uitgevoerd_door',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewplanner_uitgevoerd', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reviewplanner',
            name='voorbereid_door',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewplanner_voorbereid', to=settings.AUTH_USER_MODEL),
        ),
    ]
