# Generated by Django 5.2.7 on 2026-02-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_reviewplanner_uitgevoerd_door_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webauthnpasskey',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
