# Generated by Django 5.2.7 on 2026-02-24 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_alter_roster_options_baxterproductie'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaxterProductieSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=10, verbose_name='Machine')),
                ('timestamp', models.DateTimeField(verbose_name='Tijdstip meting')),
                ('aantal_zakjes', models.PositiveIntegerField(verbose_name='Aantal zakjes')),
            ],
            options={
                'verbose_name': 'Baxter productie snapshot',
                'verbose_name_plural': 'Baxter productie snapshots',
                'ordering': ['timestamp', 'machine_id'],
                'indexes': [models.Index(fields=['timestamp'], name='baxter_snapshot_ts_idx')],
            },
        ),
    ]
