# Generated by Django 5.2.7 on 2026-02-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_baxterproductiesnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaxterProductieSnapshotPunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField()),
                ('aantal_zakjes', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='BaxterProductieSnapshot',
        ),
        migrations.AddIndex(
            model_name='baxterproductiesnapshotpunt',
            index=models.Index(fields=['timestamp'], name='core_baxter_timesta_87b302_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='baxterproductiesnapshotpunt',
            unique_together={('machine_id', 'timestamp')},
        ),
    ]
