# Generated by Django 5.2.7 on 2026-02-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_baxterproductiesnapshotpunt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapedpage',
            name='category',
            field=models.CharField(choices=[('preparaat', 'Preparaat'), ('groep', 'Groep'), ('indicatie', 'Indicatie'), ('nhg_standaard', 'NHG-Standaard'), ('nhg_behandelrichtlijn', 'NHG-Behandelrichtlijn')], max_length=32),
        ),
    ]
