# Generated by Django 5.2.7 on 2026-03-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_alter_medicatiereviewmedgroupoverride_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='medicatiereviewmedgroupoverride',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='medicatiereviewmedgroupoverride',
            name='med_gebruik',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='medicatiereviewmedgroupoverride',
            unique_together={('patient', 'med_clean', 'med_gebruik')},
        ),
    ]
