# Generated by Django 5.2.7 on 2026-04-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_alter_medicatiereviewmedgroupoverride_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicatiereviewmedgroupoverride',
            name='target_jansen_group_id',
            field=models.IntegerField(choices=[(14, 'Allergie'), (41, 'Anabolen'), (12, 'Anemie'), (16, 'Antibiotica'), (18, 'Antimycobacteriele middelen'), (17, 'Antimycotica'), (19, 'Antivirale middelen'), (13, 'Astma/Copd'), (4, 'Bloedstolling'), (50, 'Buiten formularium?'), (26, 'Calciumregulerende middelen'), (-1, 'Contra-indicaties en allergieën'), (22, 'Corticosteroiden systemisch'), (3, 'CVRM'), (5, 'Diabetes'), (15, 'Hoest'), (23, 'Hormonen'), (28, 'Huid'), (20, 'Hypofyse- en hypothalamus en verwante verbindingen'), (39, 'Immunostimulantia'), (40, 'Immunosuppressiva'), (6, 'Jicht'), (0, 'Labwaarden'), (25, 'Lever'), (24, 'Maag/darm'), (2, 'Malen?'), (33, 'Mond'), (32, 'Neus'), (31, 'Ogen'), (37, 'Oncolytica'), (34, 'Oren'), (43, 'Overig'), (27, 'Pancreashormonen'), (10, 'Parkinson'), (8, 'Pijn'), (9, 'Psychofarmaca'), (38, 'Reuma'), (30, 'RLS'), (21, 'Schildklierhormonen'), (36, 'Sera en immunoglobulinen'), (11, 'Spierrelaxantia'), (29, 'Urogenitaal'), (35, 'Vaccins'), (1, 'Vallen?'), (7, 'Valpreventie'), (42, 'Wormen')]),
        ),
    ]
