# Generated by Django 5.2.7 on 2026-05-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0115_alter_medicatiereviewmedgroupoverride_target_jansen_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='email3',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mailadres 3'),
        ),
    ]
